---
output: stevetemplates::cv
geometry: margin=0.75in

title: "CV"
author: Gerald McQuade

jobtitle: "Teaching Associate and PhD Candidate in Economics"
address: "Lancaster University Management School · Lancaster LA1 4YX"
fontawesome: yes
email: g.mcquade1@lancaster.ac.uk
web: gerrymcquade.github.io/
updated: TRUE
rdateformat: "`r format(Sys.time(), '%b %Y')`"

keywords: Lancaster, Economics, CV, Development, Peru

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# RESEARCH EXPERIENCE

**Grupo De Análisis para el Desarrollo** | _Lima, Peru_ | Visiting Researcher \hfill 2023

* Working with local researchers to evaluate the impacts of schooling reform on siblings' skill formation and time use. Assist/monitor ongoing data collection for round 7 of Young Lives.

**Young Lives** | _Oxford, UK_ | Research Consultant \hfill 2021 - 2022

* Assisted with development and implementation of round 7 of Young Lives surveys, including travel to India and Ethiopia to deliver fieldwork training and supervise pilot surveys. Additionally developed a matched dataset of climate covariates.

**Queen Mary University London** | _London, UK_ | Research Assistant to Simon Franklin \hfill 2022

* Assisted in designing survey to measure child human capital and skills in Addis Ababa, Ethiopia.

**Lancaster University** | _Lancaster, UK_ | Research Assistant to Catherine Porter \hfill 2020 - 2021

* Conducted validation of socio-emotional measures included in Young Lives surveys, assessing suitability and performance within adolescent samples.

**Office for National Statistics** | _Newport, UK_ | Statistical Research Officer \hfill 2019

* Co-authored statistical bulletins, produced annual statistical tables and fulfilled data requests as part of the Mortality Statistics Unit.

**Health Economics Research Unit** | _Aberdeen, UK_ | Research Intern \hfill 2018

* Provided research assistance for studies on health technology and social prescribing to improve the clinical- and cost-effectiveness of health care in Scotland.

---------------------

# NON-RESEARCH EXPERIENCE

**Lancaster University** | _Lancaster, UK_ | Teaching Associate \hfill 2024-

* Teaching a range of courses in the Department of Economics, assisting with the running of the EconHub drop-in help desk and revision sessions for undergraduates. 

**Lancaster & Heriot Watt Universities** | _Lancaster, UK_ | Graduate Teaching Assistant \hfill 2019 - 2022 

* Organised and delivered seminars, workshops, and coding labs in applied micro-economics, micro-economic theory, and econometrics.

**Royal Naval Reserve** | _Edinburgh, UK_ | Officer Cadet \hfill 2014 - 2018

* Led team of officer cadets on training exercises at sea, working effectively in high-risk conditions to meet time-sensitive objectives while ensuring safe operation across Northern Europe. 

---------------------

# EDUCATION

**Lancaster University** | PhD Economics \hfill 2020 - 2024 (Expected)

**University of Oxford** | Visiting Research Student (ODID) \hfill Trinity Term 2023

**University of Edinburgh** | MSc Economics \hfill 2019 - 2020

**Heriot Watt University** | MA Economics \hfill 2015 - 2019

---------------------

# RESEARCH OUTPUT

## **Peer-reviewed publications**

"A sound methodology: Measuring experiences of violent conflict through audio self-interviews" Economic Letters, 2024. - _with Sophie von Russdorf, Laura Ahlborn, Alessandra Hidalgo & Marta Favara_ [[Paper]](https://doi.org/10.1016/j.econlet.2024.111879) [[Blog]](https://www.younglives.org.uk/news/a-sound-methodology) [[Podcast]](https://podcasts.ox.ac.uk/how-sound-methodology-improves-understanding-young-ethiopians-experience-conflict)

## **Working papers**

Some people feel the rain; others just get wet: Early-life rainfall and personality trait formation in Peru [[Draft]](https://gerrymcquade.github.io/[GM]earlyliferainfall_personalitytraits_0623.pdf)

Grandmothers and grandsons: Inter-generational effects of drought exposure in Peru

Examining sibling spillovers of a school-day extension program using a regression discontinuity design - _with Catherine Porter & Alan Sanchez_ 

## **Technical Notes**

Identifying climate shocks in Young Lives communities: Estimating weather conditions using a global gridded time series | Young Lives | _with Marta Favara_ [[Report]](https://www.younglives.org.uk/publications/identifying-climate-shocks-young-lives-communities-estimating-weather-conditions-using)

Selection and validation of socio-emotional skill measures in round 5 of the Young Lives survey | Young Lives | _with Catherine Porter, Marta Favara & Mark Mitchell_ 

## **Statistical bulletins**

Deaths related to drug poisoning in England and Wales: 2018 registrations – ONS - _with Emyr John & Asim Butt_ [[Report]](https://cy.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/bulletins/deathsrelatedtodrugpoisoninginenglandandwales/2018registrations)

<!-- --------------------- -->

<!-- # CONFERENCE PRESENTATIONS -->
## **Conference presentations**

**2023 - 2024** | 14th Bolivian Conference on Development Economics; Conferencia Internacional de Desarrollo Económico PUCP; 2nd International Conference on Development Economics; 36th European Society of Population Economics conference; 1st Welfare and Policy conference; Inaugural Essex PhD Conference in Applied Economics; NWSSDTP PhD Conference in Economics; 12th Summer School in Development Economics Workshop (_invited_); GRADE internal seminar series

**2019 - 2022** | Lancaster University PGR conference; NWSSDTP Conference; CLOSER – Preparing for the Future III;  SGPE Conference; LUMS PhD Seminar Series; Scottish Economics Conference (_student speaker_) 

<!-- --------------------- -->

<!-- # GRANTS AND AWARDS -->

<!-- **Grants**  -->

<!-- * ESRC Student-led Open Competition Masters + PhD Studentship \hfill 2019 - 2024 -->

<!-- * NWSSDTP PhD Internship Grant (6 months) | £14,000 \hfill 2023  -->

<!-- * NWSSDTP Overseas Institutional Visit Grant | £6,900 \hfill 2023 -->

<!-- **Awards** -->

<!-- * Watt Club Medal, MA economics – highest distinction \hfill 2019 -->

<!-- * Deputy Principal’s Award – overall academic excellence \hfill 2019 -->

<!-- --------------------- -->

<!-- # TEACHING -->

<!-- **Lancaster University** \hfill 2021 - 2022 -->

<!-- * Applied Economics (ECON229) | Seminars -->

<!-- * Quantitative Methods for Economics (ECON 103) | Additional Workshops -->

<!-- **Heriot Watt University** \hfill 2019 - 2020 -->

<!-- * Intermediate Microeconomics (C28IN) | Workshops -->

<!-- * Econometrics Project (C29EJ) | Labs -->

<!-- --------------------- -->

<!-- # ADDITIONAL TRAINING -->

<!-- **Advanced Applied Econometrics: Recent Methods and Issues** | University of \hfill 2022 -->

<!--  Copenhagen  -->

<!-- **GTA Economics Network Workshop** | University of Strathclyde \hfill 2022 -->

<!-- **Virtual PhD course in development economics** | IGC \hfill 2022 -->

---------------------

# OTHER RELEVANT INFORMATION

**Roles** PhD seminar organiser (2021-2022); PhD conference list creator & organiser (2022-2024)

**Proficiences** Stata, R/Rstudio (+Rmarkdown/Quarto) (Advanced);  QGIS, LaTeX (Intermediate)

**Software** sideytab [[Github repository]](https://github.com/gerrymcquade/sideytab)

**Languages** English (Native), Spanish (Conversational)
