---
output: stevetemplates::cv
geometry: margin=1in

title: "CV"
author: Gerald McQuade

jobtitle: "Teaching Associate and PhD Candidate in Economics"
address: "Lancaster University Management School · Lancaster LA1 4YX"
fontawesome: yes
email: g.mcquade1@lancaster.ac.uk
web: gerrymcquade.github.io/
updated: TRUE
rdateformat: "`r format(Sys.time(), '%b %Y')`"

keywords: Lancaster, Economics, CV, Development, Peru

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION

**Lancaster University** | PhD Economics \hfill 2020 - 2024 (Expected)

* _Advisors: Catherine Porter & Saurabh Singhal_

**University of Oxford, ODID** | Visiting Research Student \hfill Trinity term 2023

* _Host: Marta Favara_

**University of Edinburgh** | MSc Economics (SGPE) \hfill 2019 - 2020

* _Advisors: Robert Mochrie & Catherine Porter_

**Heriot Watt University** | MA Economics \hfill 2015 - 2019

* _Advisors: Robert Mochrie_

---------------------

# EXPERIENCE

**Lancaster University** | _Lancaster, UK_ | Teaching Associate \hfill 2024-

* Teaching range of courses in the Department of Economics; EconHub drop-in and revision sessions.

**Grupo De Análisis para el Desarrollo** | _Lima, Peru_ | Visiting Researcher \hfill 2023

* Working with local researchers to evaluate the impacts of schooling reform on siblings' skill formation and time use. Assist ongoing data collection for round 7 of Young Lives.

**Young Lives** | _Oxford, UK_ | External Research Consultant \hfill 2021 - 2022

* Assisted with development and implementation of round 7 surveys. Traveled to India and Ethiopia to deliver fieldwork training and supervise pilot surveys. Developed a matched data set of climate covariates.

**Queen Mary University London** | _London, UK_ | RA to Simon Franklin \hfill 2022

* Assisted in designing survey to measure child cognitive skills in Addis Ababa, Ethiopia.

**Lancaster University** | _Lancaster, UK_ | RA to Catherine Porter \hfill 2020

* Validated performance of socio-emotional measures in Young Lives round 5 survey.

**Office for National Statistics** | _Newport, UK_ | Statistical Research Officer \hfill 2019

* Authoring statistical bulletins and data requests within the Mortality Statistics Unit.

**Health Economics Research Unit** | _Aberdeen, UK_ | Research Intern \hfill 2018

* Assessing health technology and social prescribing cost-effectiveness in health care in Scotland.

---------------------

# PUBLICATIONS

## **Peer-reviewed publications**

"A sound methodology: Measuring experiences of violent conflict through audio self-interviews" Economic Letters, 2024. - _with Sophie von Russdorf, Laura Ahlborn, Alessandra Hidalgo & Marta Favara_ [[Paper]](https://doi.org/10.1016/j.econlet.2024.111879) [[Blog]](https://www.younglives.org.uk/news/a-sound-methodology) [[Podcast]](https://podcasts.ox.ac.uk/how-sound-methodology-improves-understanding-young-ethiopians-experience-conflict)

## **Working papers**

Some people feel the rain; others just get wet: Early-life rainfall and personality trait formation in Peru [[Draft]](https://gerrymcquade.github.io/[GM]earlyliferainfall_personalitytraits_0623.pdf)

Grandmothers and Grandsons: Inter-generational effects of drought exposure in Peru

Examining sibling spillovers of a school-day extension program using a regression discontinuity design - _with Catherine Porter & Alan Sanchez_ 

## **Technical Notes**

Identifying climate shocks in Young Lives communities: Estimating weather conditions using a global gridded time series | Young Lives | _with Marta Favara_ [[Report]](https://www.younglives.org.uk/publications/identifying-climate-shocks-young-lives-communities-estimating-weather-conditions-using)

Selection and validation of socio-emotional skill measures in round 5 of the Young Lives survey | Young Lives | _with Catherine Porter, Marta Favara & Mark Mitchell_ 

## **Statistical bulletins**

Deaths related to drug poisoning in England and Wales: 2018 registrations – ONS - _with Emyr John & Asim Butt_ [[Report]](https://cy.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/bulletins/deathsrelatedtodrugpoisoninginenglandandwales/2018registrations)

---------------------

# CONFERENCE PRESENTATIONS

 **2023 - 2024** 

* 14th Bolivian Conference on Development Economics; Conferencia Internacional de Desarrollo Económico PUCP; 2nd International Conference on Development Economics; 36th European Society of Population Economics conference; 1st Welfare and Policy conference; Inaugural Essex PhD Conference in Applied Economics; NWSSDTP PhD Conference in Economics; Lancaster Applied Micro Workshop; 12th Summer School in Development Economics Workshop (_invited_)

**2019 - 2022** 

* Lancaster University PGR conference; NWSSDTP Conference; CLOSER – Preparing for the Future III;  SGPE Conference; LUMS PhD Seminar Series; Scottish Economics Conference (_student speaker_) 

---------------------

# GRANTS AND AWARDS

**Grants** 

* ESRC Student-led Open Competition Masters + PhD Studentship \hfill 2019 - 2024

* NWSSDTP PhD Internship Grant (6 months) | £14,000 \hfill 2023 

* NWSSDTP Overseas Institutional Visit Grant | £6,900 \hfill 2023

**Awards**

* Watt Club Medal, MA economics – highest distinction \hfill 2019

* Deputy Principal’s Award – overall academic excellence \hfill 2019

---------------------

# TEACHING

**Lancaster University** \hfill 2021 - 2024

* Communicating Using Economic Data (ECON104) | Seminars | 2024-2025

* EconHub | Undergraduate helpdesk and revision sessions | 2024-2025

* Applied Economics (ECON229) | Seminars | 2021-2022

* Quantitative Methods for Economics (ECON 103) | Additional Workshops | 2022

* LUMS Maths and Statistics Hub | 1-to-1 Workshops | 2021-2022

**Heriot Watt University** \hfill 2019 - 2020

* Intermediate Microeconomics (C28IN) | Workshops | 2019-2020

* Econometrics Project (C29EJ) | Labs | 2019

---------------------

# ADDITIONAL TRAINING

**Advanced Applied Econometrics** | University of Copenhagen \hfill 2022

**GTA Economics Network Workshop** | University of Strathclyde \hfill 2022

**Virtual PhD course in development economics** | IGC \hfill 2022

---------------------

# OTHER RELEVANT INFORMATION

**Roles**  Lancaster University Economics PhD seminar organiser \hfill 2021-2022

**Proficiences** Stata, R/Rstudio (including Rmarkdown, Quarto), QGIS, LaTeX

**Software** sideytab [[Github repository]](https://github.com/gerrymcquade/sideytab)

**Languages** English (Native), Spanish (CEFR level A2)
